name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    concurrency:
      group: crocheteria-api-deploy
      cancel-in-progress: true

    steps:
      - name: Deploy container
        run: |
          cd /srv/projects/crocheteria-api
          docker compose -p crocheteria-api pull
          docker compose -p crocheteria-api up -d
